#!/bin/bash

export DESKTOP_CORE_NAME="ZY-Player"
export DESKTOP_CORE_BIN_NAME="$DESKTOP_CORE_NAME"
export DESKTOP_CORE_VERSION=v2.8.8
export DESKTOP_CORE_ORG="Hunlongyu"

export DESKTOP_CORE_RELEASE_DOWNLOAD="https://github.com/${DESKTOP_CORE_ORG}/ZY-Player/releases/download"

export DESKTOP_CORE_CHECKSUMS=(
  v2.8.8#darwin#arm64#c00d2315d564f800fbb6d67fb3e3620276cfc0669737b20fdbc54d39b87596ab
  v2.8.8#darwin#amd64#c00d2315d564f800fbb6d67fb3e3620276cfc0669737b20fdbc54d39b87596ab
)
